name: TrMenu
main: me.arasple.mc.trmenu.TrMenu

description: Advanced & Dynamic menus for Minecraft

api-version: 1.13
version: 1.15

github: https://github.com/Arasple/TrMenu

softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - TrChat
  - Yum
  - ChestCommands

author: Arasple
