name: TrMenu
main: me.arasple.mc.trmenu.TrMenu

description: Advanced & Dynamic menus for Minecraft

api-version: 1.13
version: ${version}

built-time: ${built}

github: https://github.com/Arasple/TrMenu

softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - TabooMenu

author: Arasple
