name: TrMenu
main: me.arasple.mc.trmenu.TrMenu

description: A powerful advanced menu plugin with animated item support

api-version: 1.13
version: ${version}

github: https://github.com/Arasple/TrMenu
qq: 1197897763

depend:
  - PlaceholderAPI

softdepend:
  - HeadDatabase

author: Arasple
