name: ${name}
main: ${main}
main-transfer: ${mainTransfer}

author: Arasple

api-version: 1.13
version: ${version}

github: https://github.com/Arasple/${name}
description: Modern & Advanced Menu-Plugin for Minecraft Servers

softdepend:
  - PlaceholderAPI
  - Vault
  - Cronus
  - PlayerPoints
  - HeadDatabase
  - Oraxen
  - WorldGuard
  - SkinRestorer

built-time: ${built}
built-by: ${builder}
built-os: ${os}