name: ${name}
main: ${main}

author: Arasple

api-version: 1.13
lib-version: ${taboolib}
version: ${version}

github: https://github.com/Arasple/${name}
description: Modern & Advanced Menu-Plugin for Minecraft Servers

softdepend:
  - PlaceholderAPI
  - Vault
  - Cronus
  - PlayerPoints
  - HeadDatabase
  - Oraxen
  - WorldGuard
  - SkinsRestorer

built-time: ${built}
built-by: ${builder}
built-os: ${os}