name: ${name}
main: ${main}

authors:
  - Arasple
  - Bkm016

api-version: "1.13"
lib-version: ${taboolib}
lib-download: ${libDownload}
version: ${version}

github: https://github.com/Arasple/${name}
description: Modern & Advanced Menu-Plugin for Minecraft Servers

softdepend:
  - PlaceholderAPI
  - Vault
  - CMI
  - Cronus
  - PlayerPoints
  - HeadDatabase
  - Oraxen
  - SkinsRestorer
  - TokenManager

built-time: ${built}
built-by: ${builder}
built-os: ${os}