################################################################################
#
#  ____________________   _____  __________________   ____ ___
#\__    ___\______   \ /     \ \_   _____/\      \ |    |   \
#  |    |   |       _//  \ /  \ |    __)_ /   |   \|    |   /
#  |    |   |    |   /    Y    \|        /    |    |    |  /
#  |____|   |____|_  \____|__  /_______  \____|__  |______/
#                  \/        \/        \/        \/
#
# 高级动态菜单插件
#
# https://github.com/Arasple/TrMenu
#
################################################################################
CONFIG-VERSION: 0

# 相关选项
OPTIONS:
  # 原版材质读取时智能相似度识别最小百分比
  MATERIAL-SIMILAR-DEGREE: 0.8
  # 最小的点击延时, 防容器点击事件刷屏 (ms)
  ANTI-CLICK-SPAM: 200
  # 是否启用菜单自动重载
  # * 插件将对已载入的菜单文件监听文件改动
  # * 并自动重载, 包括刷新已打开的菜单
  # * 如果有任何错误发生则不通知、重载
  MENU-FILE-LISTENER:
    # 是否启用
    ENABLE: true
    # 成功的加载是否通知控制台
    NOTIFY: true

# 自定义路径载入菜单
# (plugins/TrMenu/menus 目录及其子目录下的菜单默认均会加载)
MENU-FILES:
  - 'plugins/XXX/zzz.yml'
