# 相关注解、用法请查阅 https://github.com/Arasple/TrMenu
CONFIG-VERSION: 0

LOCALE-PRIORITY:
  - en_US
  - zh_CN

OPTIONS:
  MATERIAL-SIMILAR-DEGREE: 0.8
  ANTI-CLICK-SPAM: 200
  MENU-FILE-LISTENER:
    ENABLE: true
    NOTIFY: true

# Custom loading files as menus
MENU-FILES: []
