################################################################################
#
#  ____________________   _____  __________________   ____ ___
#\__    ___\______   \ /     \ \_   _____/\      \ |    |   \
#  |    |   |       _//  \ /  \ |    __)_ /   |   \|    |   /
#  |    |   |    |   /    Y    \|        /    |    |    |  /
#  |____|   |____|_  \____|__  /_______  \____|__  |______/
#                  \/        \/        \/        \/
#
# 高级动态菜单插件
#
# https://github.com/Arasple/TrMenu
#
################################################################################
CONFIG-VERSION: 0

# 相关选项
OPTIONS:
  # 原版材质读取时智能相似度识别最小百分比
  MATERIAL-SIMILAR-DEGREE: 0.8
  # 最小的点击延时, 防容器点击事件刷屏 (ms)
  ANTI-CLICK-SPAM: 200

# 自定义路径载入菜单
# (plugins/TrMenu/menus 目录及其子目录下的菜单默认均会加载)
MENU-FILES:
  - 'plugins/XXX/zzz.yml'
