# TrMenu Wiki: https://trmenu.trixey.cn

# Do not change
CONFIG-VERSION: 0

# Locale loading priority
# Put your locale in the first
# Contributing Translations: https://trmenu.trixey.cn/other/locale
LOCALE-PRIORITY:
  - en_US
  - zh_CN
  - zh_TW
  - vi_VN
  - th_TH
  - es_ES

# Options
OPTIONS:
  # Enable this, the plugin will not display the logo when loading
  SILENT: false
  # Similar material matches
  MATERIAL-SIMILAR-DEGREE: 0.8
  # Anti inventory click spam (millisecs)
  ANTI-CLICK-SPAM: 200
  # Should enable the menu file listener?
  MENU-FILE-LISTENER:
    ENABLE: true
    NOTIFY: true
  # The words used to cancel a catcher action (Support Regex)
  CATCHER-CANCEL-WORDS:
    - 'return|break'
    - 'quit'
    - 'exit'
    - 'cancel'

# Only for 1.9+ servers
# Each option is only for one menu
SHORTCUT-OPEN:
  OFFHAND: null
  SNEAKING-OFFHAND: 'example'

# Custom loading files as menus
MENU-FILES: []

# Create menus inside the settings file
MENUS:
  - internalMenu:
      title: 'Internal Menu in settings.yml'
      shape:
        - '#########'
        - '    |    '
        - '#########'
      buttons:
        '#':
          display:
            mats: green stained glass pane
        '|':
          display:
            mats: apple
            name: '&6Nice to meet you~'
