name: CI

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  gradle:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildJar
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/*.jar